title: "Your Name"
description: "Astrophysics Student | IISER Kolkata"
theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
url: "https://birupakshade.github.io"
author:
  name: "Your Name"
  avatar: "/assets/images/Airbrush-Image-Enhancer-1755788403098.jpg"
  bio: "BS-MS Student at IISER Kolkata | Astrophysics Enthusiast"
  location: "Kolkata, India"
  links:
    - label: "CV"
      url: "/assets/files/cv.pdf"
    - label: "GitHub"
      url: "https://github.com/yourusername"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/yourprofile"
minimal_mistakes_skin: "default"
