title: "Birupaksha De | Astrophysics"
description: "BS-MS Student at IISER Kolkata | Exploring the Universe"
theme: minima   # you can switch later
url: "https://birupakshade.github.io"
baseurl: ""   # leave blank for user site
